
 package ru.sbrf.gg.load.builder;

 import ru.sbrf.gg.load.TableInfo;
 import com.sbt.DelimetedStringParser;
 import ru.sbrf.gg.load.builder.ObjectBuilder;

 import ru.sbt.kmdtransform.TransformType.*;

 public class DepoHistBuilder implements ObjectBuilder {
     @Override public Object build(String line, TableInfo tableInfo) {
         com.sbt.cdm.model.extension.deposit.DepoHist r = new com.sbt.cdm.model.extension.deposit.DepoHist();
         int[] indexes = new int[]{0, 0, line.length()};

         r.id = DelimetedStringParser._long(0, line, indexes);
r.objectId = DelimetedStringParser._long(0, line, indexes);
r.colocationKey = DelimetedStringParser._long(1, line, indexes);
r.rootParticle_DPL_id = DelimetedStringParser._long(2, line, indexes);
r.operationRun_DPL_id = DelimetedStringParser._long(3, line, indexes);
r.cardhistAtmid = DelimetedStringParser.str(4, line, indexes);
r.cardhistAuthcode = DelimetedStringParser.str(5, line, indexes);
r.cardhistAuthkind = DelimetedStringParser._int(6, line, indexes);
r.cardhistCardno = DelimetedStringParser.str(7, line, indexes);
r.cardhistMerchantno = DelimetedStringParser.str(8, line, indexes);
r.cardhistTxcash = DelimetedStringParser.bigDecimal(9, line, indexes);
r.cardhistTxcurrency = DelimetedStringParser._int(10, line, indexes);
r.cardhistTxid = DelimetedStringParser._int(11, line, indexes);
r.cardhistTxtime = DelimetedStringParser.date(12, line, indexes);
r.depohistAssignday = DelimetedStringParser.date(13, line, indexes);
r.depohistAssminbalance = DelimetedStringParser.bigDecimal(14, line, indexes);
r.depohistBalance = DelimetedStringParser.bigDecimal(15, line, indexes);
r.depohistBalanceOwn = DelimetedStringParser.bigDecimal(16, line, indexes);
r.depohistSubsidy = DelimetedStringParser.bigDecimal(17, line, indexes);
r.depohist_branchno = DelimetedStringParser._int(18, line, indexes);
r.depohistCardrptday = DelimetedStringParser.date(19, line, indexes);
r.depohistCashsource = DelimetedStringParser._int(20, line, indexes);
r.depohistChequecnt = DelimetedStringParser._int(21, line, indexes);
r.depohistClerk = DelimetedStringParser._int(22, line, indexes);
r.depohistConverCurrency = DelimetedStringParser._int(23, line, indexes);
r.depohistConverOpcash = DelimetedStringParser.bigDecimal(24, line, indexes);
r.depohistCreditaccount = DelimetedStringParser.str(25, line, indexes);
r.depohistDebitaccount = DelimetedStringParser.str(26, line, indexes);
r.depohistDepositrate = DelimetedStringParser.bigDecimal(27, line, indexes);
r.depohistExpirationday = DelimetedStringParser.date(28, line, indexes);
r.depohistExpminbalance = DelimetedStringParser.bigDecimal(29, line, indexes);
r.depohistExproverdraft = DelimetedStringParser.bigDecimal(30, line, indexes);
r.depohistExproverdraftint = DelimetedStringParser.bigDecimal(31, line, indexes);
r.depohistExternalkind = DelimetedStringParser._int(32, line, indexes);
r.depohistFlagCash = DelimetedStringParser._int(33, line, indexes);
r.depohistGrantOper = DelimetedStringParser._int(34, line, indexes);
r.depohistHeirno = DelimetedStringParser._int(35, line, indexes);
r.depohist_tb = DelimetedStringParser._int(36, line, indexes);
r.depohistInserttime = DelimetedStringParser.date(37, line, indexes);
r.depohistInterest = DelimetedStringParser.bigDecimal(38, line, indexes);
r.depohistInterestf = DelimetedStringParser.bigDecimal(39, line, indexes);
r.depohistIscashdispenser = DelimetedStringParser._int(40, line, indexes);
r.depohistIsmanual = DelimetedStringParser._int(41, line, indexes);
r.depohistIsmoffice = DelimetedStringParser._int(42, line, indexes);
r.depohistJrnno = DelimetedStringParser._int(43, line, indexes);
r.depohistMaxamount = DelimetedStringParser.bigDecimal(44, line, indexes);
r.depohistMaxamountrate = DelimetedStringParser.bigDecimal(45, line, indexes);
r.depohistNDprice = DelimetedStringParser._long(46, line, indexes);
r.depohistOffcashbalanceb = DelimetedStringParser.bigDecimal(48, line, indexes);
r.depohistOffice = DelimetedStringParser._int(49, line, indexes);
r.depohistOfficetransday = DelimetedStringParser.date(50, line, indexes);
r.depohistOpcash = DelimetedStringParser.bigDecimal(51, line, indexes);
r.depohistOpcashcost = DelimetedStringParser.bigDecimal(52, line, indexes);
r.depohistOpcode = DelimetedStringParser._int(53, line, indexes);
r.depohistOpday = DelimetedStringParser.date(54, line, indexes);
r.depohistOpencash = DelimetedStringParser.bigDecimal(55, line, indexes);
r.depohistOpkind = DelimetedStringParser._int(56, line, indexes);
r.depohistOpno = DelimetedStringParser._int(57, line, indexes);
r.depohistOptransday = DelimetedStringParser.date(58, line, indexes);
r.depohistOrderno = DelimetedStringParser.str(59, line, indexes);
r.depohistMinBalanceMonth = DelimetedStringParser.bigDecimal(60, line, indexes);
r.depohistBalanceOwnProlong = DelimetedStringParser.bigDecimal(61, line, indexes);
r.depohistOverdraft = DelimetedStringParser.bigDecimal(62, line, indexes);
r.depohistOverdraftint = DelimetedStringParser.bigDecimal(63, line, indexes);
r.depohistPairAccount = DelimetedStringParser.str(64, line, indexes);
r.depohistPartrate = DelimetedStringParser.bigDecimal(65, line, indexes);
r.depohistPayrollday = DelimetedStringParser.date(66, line, indexes);
r.depohistPayAddFirst = DelimetedStringParser.date(67, line, indexes);
r.depohistPercentsrate = DelimetedStringParser.bigDecimal(68, line, indexes);
r.depohistPinacceptflag = DelimetedStringParser._int(69, line, indexes);
r.depohistProlongday = DelimetedStringParser.date(70, line, indexes);
r.depohistRatesource = DelimetedStringParser._int(71, line, indexes);
r.depohistReason = DelimetedStringParser._int(72, line, indexes);
r.depohistSbookendday = DelimetedStringParser.date(73, line, indexes);
r.depohistSourcedocday = DelimetedStringParser.date(74, line, indexes);
r.depohistSourcedocno = DelimetedStringParser.str(75, line, indexes);
r.depohistSourcedocoriginator = DelimetedStringParser.str(76, line, indexes);
r.depohistState = DelimetedStringParser._int(77, line, indexes);
r.depohistSubsys = DelimetedStringParser._int(78, line, indexes);
r.depohistSumobnaloperation = DelimetedStringParser.bigDecimal(79, line, indexes);
r.depohistTaxableprofit = DelimetedStringParser.bigDecimal(80, line, indexes);
r.depohistTaxableprofitcost = DelimetedStringParser.bigDecimal(81, line, indexes);
r.depohistTermsok = DelimetedStringParser._int(82, line, indexes);
r.depohistTurncode = DelimetedStringParser._int(83, line, indexes);
r.depohistUsedtaxexemptions = DelimetedStringParser.bigDecimal(84, line, indexes);
r.depohistVHzap2 = DelimetedStringParser._int(85, line, indexes);
r.depohistWarrantkind = DelimetedStringParser._int(86, line, indexes);
r.depohistWarrantno = DelimetedStringParser.str(87, line, indexes);
r.offcashcompInfo = DelimetedStringParser.str(88, line, indexes);
r.offcashcompOpday = DelimetedStringParser.date(89, line, indexes);
r.offcashcompOpno = DelimetedStringParser._int(90, line, indexes);
r.offcashcompOrdno = DelimetedStringParser.str(91, line, indexes);
r.offcashcompSsagency = DelimetedStringParser.str(92, line, indexes);
r.offcashcompSsn = DelimetedStringParser.str(93, line, indexes);
r.offcashcompVDnum1 = DelimetedStringParser._int(94, line, indexes);
r.offcashcompVDsum1 = DelimetedStringParser.bigDecimal(95, line, indexes);
r.offcashcompVDsum2 = DelimetedStringParser.bigDecimal(96, line, indexes);
r.offcashcompVDsum3 = DelimetedStringParser.bigDecimal(97, line, indexes);
r.offcashcompVDsum4 = DelimetedStringParser.bigDecimal(98, line, indexes);
r.offcashcompVDsum5 = DelimetedStringParser.bigDecimal(99, line, indexes);
r.offcashcompVDsum6 = DelimetedStringParser.bigDecimal(100, line, indexes);
r.offcashcompVDsum7 = DelimetedStringParser.bigDecimal(101, line, indexes);
r.category_DPL_id = DelimetedStringParser._long(102, line, indexes);
r.depohistrgCpBalance = DelimetedStringParser.bigDecimal(103, line, indexes);
r.depohistrgCpOpcash = DelimetedStringParser.bigDecimal(104, line, indexes);
r.depohistrgSprBalance = DelimetedStringParser.bigDecimal(105, line, indexes);
r.depohistrgSprOpcash = DelimetedStringParser.bigDecimal(106, line, indexes);
r.depohistrgCn1Balance = DelimetedStringParser.bigDecimal(107, line, indexes);
r.depohistrgCn1Opcash = DelimetedStringParser.bigDecimal(108, line, indexes);
r.depohistrgCn2Balance = DelimetedStringParser.bigDecimal(109, line, indexes);
r.depohistrgCn2Opcash = DelimetedStringParser.bigDecimal(110, line, indexes);
r.enrollType = DelimetedStringParser._int(111, line, indexes);
r.partition_DPL_id = DelimetedStringParser._long(112, line, indexes);

         return r;
     }
 }
            
