
 package ru.sbrf.gg.load.builder

 import ru.sbrf.gg.load.TableInfo
 import ru.sbt.kmdtransform.TransformType._

 class DCardBuilder extends ObjectBuilder {
     def build(line: Array[String], tableInfo: TableInfo): Any = {
         val r = new com.sbt.cdm.model.extension.deposit.DCard()

         r.id = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.objectId = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.colocationKey = LONG.fromStr(line(1)).asInstanceOf[java.lang.Long]
r.rootParticle_DPL_id = LONG.fromStr(line(2)).asInstanceOf[java.lang.Long]
r.plasticCardInst_DPL_id = LONG.fromStr(line(3)).asInstanceOf[java.lang.Long]
r.dcardAircode = STRING.fromStr(line(4)).asInstanceOf[java.lang.String]
r.dcardAirnumber = STRING.fromStr(line(5)).asInstanceOf[java.lang.String]
r.dcardAutopaymentState = LONG.fromStr(line(6)).asInstanceOf[java.lang.Long]
r.dcardAutopaymentSumma = BIGDECIMAL.fromStr(line(7)).asInstanceOf[java.math.BigDecimal]
r.dcardBlockcode = LONG.fromStr(line(8)).asInstanceOf[java.lang.Long]
r.dcardBlockdate = DATE_TIME.fromStr(line(9)).asInstanceOf[java.util.Date]
r.dcard_branchno = LONG.fromStr(line(10)).asInstanceOf[java.lang.Long]
r.dcardCardmadeenddate = DATE_TIME.fromStr(line(11)).asInstanceOf[java.util.Date]
r.dcardCardmadeloaddate = DATE_TIME.fromStr(line(12)).asInstanceOf[java.util.Date]
r.dcardCardmadenumber = STRING.fromStr(line(13)).asInstanceOf[java.lang.String]
r.dcardChangeBranchno = LONG.fromStr(line(14)).asInstanceOf[java.lang.Long]
r.dcardChangeClerk = LONG.fromStr(line(15)).asInstanceOf[java.lang.Long]
r.dcardChangeDay = DATE_TIME.fromStr(line(16)).asInstanceOf[java.util.Date]
r.dcardChangeOffice = LONG.fromStr(line(17)).asInstanceOf[java.lang.Long]
r.dcardChangeType = LONG.fromStr(line(18)).asInstanceOf[java.lang.Long]
r.dcardClaimdate = DATE_TIME.fromStr(line(19)).asInstanceOf[java.util.Date]
r.dcardClaimiask = LONG.fromStr(line(20)).asInstanceOf[java.lang.Long]
r.dcardClient = LONG.fromStr(line(21)).asInstanceOf[java.lang.Long]
r.dcardCodecard = LONG.fromStr(line(22)).asInstanceOf[java.lang.Long]
r.dcardCodefortariff = LONG.fromStr(line(23)).asInstanceOf[java.lang.Long]
r.dcardCodetariffchange = LONG.fromStr(line(24)).asInstanceOf[java.lang.Long]
r.dcardContrdate = DATE_TIME.fromStr(line(25)).asInstanceOf[java.util.Date]
r.dcardCurissue = LONG.fromStr(line(26)).asInstanceOf[java.lang.Long]
r.dcardDaylimcard = BIGDECIMAL.fromStr(line(27)).asInstanceOf[java.math.BigDecimal]
r.dcardDepokind = LONG.fromStr(line(28)).asInstanceOf[java.lang.Long]
r.dcardDeposubkind = LONG.fromStr(line(29)).asInstanceOf[java.lang.Long]
r.dcardDrn = STRING.fromStr(line(30)).asInstanceOf[java.lang.String]
r.dcardEndcontrdate = DATE_TIME.fromStr(line(31)).asInstanceOf[java.util.Date]
r.dcardHashcard = STRING.fromStr(line(32)).asInstanceOf[java.lang.String]
r.dcardHelpdate = DATE_TIME.fromStr(line(33)).asInstanceOf[java.util.Date]
r.dcardHoldercode = LONG.fromStr(line(34)).asInstanceOf[java.lang.Long]
r.dcard_tb = LONG.fromStr(line(35)).asInstanceOf[java.lang.Long]
r.dcardInsurcard = BIGDECIMAL.fromStr(line(36)).asInstanceOf[java.math.BigDecimal]
r.dcardIschange = LONG.fromStr(line(37)).asInstanceOf[java.lang.Long]
r.dcardIsclnpresent = LONG.fromStr(line(38)).asInstanceOf[java.lang.Long]
r.dcardIssalary = LONG.fromStr(line(39)).asInstanceOf[java.lang.Long]
r.dcardIssueby = LONG.fromStr(line(40)).asInstanceOf[java.lang.Long]
r.dcardIsvip = LONG.fromStr(line(41)).asInstanceOf[java.lang.Long]
r.dcardLimcard = BIGDECIMAL.fromStr(line(42)).asInstanceOf[java.math.BigDecimal]
r.dcardMarklock = LONG.fromStr(line(43)).asInstanceOf[java.lang.Long]
r.dcardMarklockdate = DATE_TIME.fromStr(line(44)).asInstanceOf[java.util.Date]
r.dcardMarklockstr = STRING.fromStr(line(45)).asInstanceOf[java.lang.String]
r.dcardMbOperator = LONG.fromStr(line(46)).asInstanceOf[java.lang.Long]
r.dcardMbPhone = STRING.fromStr(line(47)).asInstanceOf[java.lang.String]
r.dcardMbType = LONG.fromStr(line(48)).asInstanceOf[java.lang.Long]
r.dcardMonthlimcard = BIGDECIMAL.fromStr(line(49)).asInstanceOf[java.math.BigDecimal]
r.dcardNumbancard = LONG.fromStr(line(50)).asInstanceOf[java.lang.Long]
r.dcardNumcard = STRING.fromStr(line(51)).asInstanceOf[java.lang.String]
r.dcardNumcardclaim = STRING.fromStr(line(52)).asInstanceOf[java.lang.String]
r.dcardNumcardold = STRING.fromStr(line(53)).asInstanceOf[java.lang.String]
r.dcardNumcontrcard = LONG.fromStr(line(54)).asInstanceOf[java.lang.Long]
r.dcardNumpaycard = LONG.fromStr(line(55)).asInstanceOf[java.lang.Long]
r.dcardOffice = LONG.fromStr(line(56)).asInstanceOf[java.lang.Long]
r.dcardOverdraft = BIGDECIMAL.fromStr(line(57)).asInstanceOf[java.math.BigDecimal]
r.dcardPayissue = BIGDECIMAL.fromStr(line(58)).asInstanceOf[java.math.BigDecimal]
r.dcardPresenceallow = LONG.fromStr(line(59)).asInstanceOf[java.lang.Long]
r.dcardPresenceclaim = LONG.fromStr(line(60)).asInstanceOf[java.lang.Long]
r.dcardQuaopercard = LONG.fromStr(line(61)).asInstanceOf[java.lang.Long]
r.dcardReasonchange = LONG.fromStr(line(62)).asInstanceOf[java.lang.Long]
r.dcardReturndate = DATE_TIME.fromStr(line(63)).asInstanceOf[java.util.Date]
r.dcardRptallow = LONG.fromStr(line(64)).asInstanceOf[java.lang.Long]
r.dcardRptinternet = LONG.fromStr(line(65)).asInstanceOf[java.lang.Long]
r.dcardRptpost = LONG.fromStr(line(66)).asInstanceOf[java.lang.Long]
r.dcardSin = STRING.fromStr(line(67)).asInstanceOf[java.lang.String]
r.dcardSnils = STRING.fromStr(line(68)).asInstanceOf[java.lang.String]
r.dcardSubcard = LONG.fromStr(line(69)).asInstanceOf[java.lang.Long]
r.dcardSumbancard = BIGDECIMAL.fromStr(line(70)).asInstanceOf[java.math.BigDecimal]
r.dcardSumpaycard = BIGDECIMAL.fromStr(line(71)).asInstanceOf[java.math.BigDecimal]
r.dcardTariffservcur = BIGDECIMAL.fromStr(line(72)).asInstanceOf[java.math.BigDecimal]
r.dcardTariffservnext = BIGDECIMAL.fromStr(line(73)).asInstanceOf[java.math.BigDecimal]
r.dcardTextcontrol = STRING.fromStr(line(74)).asInstanceOf[java.lang.String]
r.dcardTypeSbnkd = LONG.fromStr(line(75)).asInstanceOf[java.lang.Long]
r.dcardTypecard = LONG.fromStr(line(76)).asInstanceOf[java.lang.Long]
r.dcardUecClaimNumber = STRING.fromStr(line(77)).asInstanceOf[java.lang.String]
r.dcardUecClaimSeries = STRING.fromStr(line(78)).asInstanceOf[java.lang.String]
r.dcardUsebio = LONG.fromStr(line(79)).asInstanceOf[java.lang.Long]
r.dcardUsepin = LONG.fromStr(line(80)).asInstanceOf[java.lang.Long]
r.dcardDcardMain = COMPOSEKEY.fromStr(line(81)).asInstanceOf[java.lang.Long]
r.category_DPL_id = LONG.fromStr(line(82)).asInstanceOf[java.lang.Long]
r.partition_DPL_id = LONG.fromStr(line(83)).asInstanceOf[java.lang.Long]

         r
     }
 }
            
