
 package ru.sbrf.gg.load.builder

 import ru.sbrf.gg.load.TableInfo
 import ru.sbt.kmdtransform.TransformType._

 class DepoHistBuilder extends ObjectBuilder {
     def build(line: Array[String], tableInfo: TableInfo): Any = {
         val r = new com.sbt.cdm.model.extension.deposit.DepoHist()

         r.id = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.objectId = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.colocationKey = LONG.fromStr(line(1)).asInstanceOf[java.lang.Long]
r.rootParticle_DPL_id = LONG.fromStr(line(2)).asInstanceOf[java.lang.Long]
r.operationRun_DPL_id = LONG.fromStr(line(3)).asInstanceOf[java.lang.Long]
r.cardhistAtmid = STRING.fromStr(line(4)).asInstanceOf[java.lang.String]
r.cardhistAuthcode = STRING.fromStr(line(5)).asInstanceOf[java.lang.String]
r.cardhistAuthkind = INTEGER.fromStr(line(6)).asInstanceOf[java.lang.Integer]
r.cardhistCardno = STRING.fromStr(line(7)).asInstanceOf[java.lang.String]
r.cardhistMerchantno = STRING.fromStr(line(8)).asInstanceOf[java.lang.String]
r.cardhistTxcash = BIGDECIMAL.fromStr(line(9)).asInstanceOf[java.math.BigDecimal]
r.cardhistTxcurrency = INTEGER.fromStr(line(10)).asInstanceOf[java.lang.Integer]
r.cardhistTxid = INTEGER.fromStr(line(11)).asInstanceOf[java.lang.Integer]
r.cardhistTxtime = DATE_TIME.fromStr(line(12)).asInstanceOf[java.util.Date]
r.depohistAssignday = DATE_TIME.fromStr(line(13)).asInstanceOf[java.util.Date]
r.depohistAssminbalance = BIGDECIMAL.fromStr(line(14)).asInstanceOf[java.math.BigDecimal]
r.depohistBalance = BIGDECIMAL.fromStr(line(15)).asInstanceOf[java.math.BigDecimal]
r.depohistBalanceOwn = BIGDECIMAL.fromStr(line(16)).asInstanceOf[java.math.BigDecimal]
r.depohistSubsidy = BIGDECIMAL.fromStr(line(17)).asInstanceOf[java.math.BigDecimal]
r.depohist_branchno = INTEGER.fromStr(line(18)).asInstanceOf[java.lang.Integer]
r.depohistCardrptday = DATE_TIME.fromStr(line(19)).asInstanceOf[java.util.Date]
r.depohistCashsource = INTEGER.fromStr(line(20)).asInstanceOf[java.lang.Integer]
r.depohistChequecnt = INTEGER.fromStr(line(21)).asInstanceOf[java.lang.Integer]
r.depohistClerk = INTEGER.fromStr(line(22)).asInstanceOf[java.lang.Integer]
r.depohistConverCurrency = INTEGER.fromStr(line(23)).asInstanceOf[java.lang.Integer]
r.depohistConverOpcash = BIGDECIMAL.fromStr(line(24)).asInstanceOf[java.math.BigDecimal]
r.depohistCreditaccount = STRING.fromStr(line(25)).asInstanceOf[java.lang.String]
r.depohistDebitaccount = STRING.fromStr(line(26)).asInstanceOf[java.lang.String]
r.depohistDepositrate = BIGDECIMAL.fromStr(line(27)).asInstanceOf[java.math.BigDecimal]
r.depohistExpirationday = DATE_TIME.fromStr(line(28)).asInstanceOf[java.util.Date]
r.depohistExpminbalance = BIGDECIMAL.fromStr(line(29)).asInstanceOf[java.math.BigDecimal]
r.depohistExproverdraft = BIGDECIMAL.fromStr(line(30)).asInstanceOf[java.math.BigDecimal]
r.depohistExproverdraftint = BIGDECIMAL.fromStr(line(31)).asInstanceOf[java.math.BigDecimal]
r.depohistExternalkind = INTEGER.fromStr(line(32)).asInstanceOf[java.lang.Integer]
r.depohistFlagCash = INTEGER.fromStr(line(33)).asInstanceOf[java.lang.Integer]
r.depohistGrantOper = INTEGER.fromStr(line(34)).asInstanceOf[java.lang.Integer]
r.depohistHeirno = INTEGER.fromStr(line(35)).asInstanceOf[java.lang.Integer]
r.depohist_tb = INTEGER.fromStr(line(36)).asInstanceOf[java.lang.Integer]
r.depohistInserttime = DATE_TIME.fromStr(line(37)).asInstanceOf[java.util.Date]
r.depohistInterest = BIGDECIMAL.fromStr(line(38)).asInstanceOf[java.math.BigDecimal]
r.depohistInterestf = BIGDECIMAL.fromStr(line(39)).asInstanceOf[java.math.BigDecimal]
r.depohistIscashdispenser = INTEGER.fromStr(line(40)).asInstanceOf[java.lang.Integer]
r.depohistIsmanual = INTEGER.fromStr(line(41)).asInstanceOf[java.lang.Integer]
r.depohistIsmoffice = INTEGER.fromStr(line(42)).asInstanceOf[java.lang.Integer]
r.depohistJrnno = INTEGER.fromStr(line(43)).asInstanceOf[java.lang.Integer]
r.depohistMaxamount = BIGDECIMAL.fromStr(line(44)).asInstanceOf[java.math.BigDecimal]
r.depohistMaxamountrate = BIGDECIMAL.fromStr(line(45)).asInstanceOf[java.math.BigDecimal]
r.depohistNDprice = LONG.fromStr(line(46)).asInstanceOf[java.lang.Long]
r.depohistOffcashbalanceb = BIGDECIMAL.fromStr(line(48)).asInstanceOf[java.math.BigDecimal]
r.depohistOffice = INTEGER.fromStr(line(49)).asInstanceOf[java.lang.Integer]
r.depohistOfficetransday = DATE_TIME.fromStr(line(50)).asInstanceOf[java.util.Date]
r.depohistOpcash = BIGDECIMAL.fromStr(line(51)).asInstanceOf[java.math.BigDecimal]
r.depohistOpcashcost = BIGDECIMAL.fromStr(line(52)).asInstanceOf[java.math.BigDecimal]
r.depohistOpcode = INTEGER.fromStr(line(53)).asInstanceOf[java.lang.Integer]
r.depohistOpday = DATE_TIME.fromStr(line(54)).asInstanceOf[java.util.Date]
r.depohistOpencash = BIGDECIMAL.fromStr(line(55)).asInstanceOf[java.math.BigDecimal]
r.depohistOpkind = INTEGER.fromStr(line(56)).asInstanceOf[java.lang.Integer]
r.depohistOpno = INTEGER.fromStr(line(57)).asInstanceOf[java.lang.Integer]
r.depohistOptransday = DATE_TIME.fromStr(line(58)).asInstanceOf[java.util.Date]
r.depohistOrderno = STRING.fromStr(line(59)).asInstanceOf[java.lang.String]
r.depohistMinBalanceMonth = BIGDECIMAL.fromStr(line(60)).asInstanceOf[java.math.BigDecimal]
r.depohistBalanceOwnProlong = BIGDECIMAL.fromStr(line(61)).asInstanceOf[java.math.BigDecimal]
r.depohistOverdraft = BIGDECIMAL.fromStr(line(62)).asInstanceOf[java.math.BigDecimal]
r.depohistOverdraftint = BIGDECIMAL.fromStr(line(63)).asInstanceOf[java.math.BigDecimal]
r.depohistPairAccount = STRING.fromStr(line(64)).asInstanceOf[java.lang.String]
r.depohistPartrate = BIGDECIMAL.fromStr(line(65)).asInstanceOf[java.math.BigDecimal]
r.depohistPayrollday = DATE_TIME.fromStr(line(66)).asInstanceOf[java.util.Date]
r.depohistPayAddFirst = DATE_TIME.fromStr(line(67)).asInstanceOf[java.util.Date]
r.depohistPercentsrate = BIGDECIMAL.fromStr(line(68)).asInstanceOf[java.math.BigDecimal]
r.depohistPinacceptflag = INTEGER.fromStr(line(69)).asInstanceOf[java.lang.Integer]
r.depohistProlongday = DATE_TIME.fromStr(line(70)).asInstanceOf[java.util.Date]
r.depohistRatesource = INTEGER.fromStr(line(71)).asInstanceOf[java.lang.Integer]
r.depohistReason = INTEGER.fromStr(line(72)).asInstanceOf[java.lang.Integer]
r.depohistSbookendday = DATE_TIME.fromStr(line(73)).asInstanceOf[java.util.Date]
r.depohistSourcedocday = DATE_TIME.fromStr(line(74)).asInstanceOf[java.util.Date]
r.depohistSourcedocno = STRING.fromStr(line(75)).asInstanceOf[java.lang.String]
r.depohistSourcedocoriginator = STRING.fromStr(line(76)).asInstanceOf[java.lang.String]
r.depohistState = INTEGER.fromStr(line(77)).asInstanceOf[java.lang.Integer]
r.depohistSubsys = INTEGER.fromStr(line(78)).asInstanceOf[java.lang.Integer]
r.depohistSumobnaloperation = BIGDECIMAL.fromStr(line(79)).asInstanceOf[java.math.BigDecimal]
r.depohistTaxableprofit = BIGDECIMAL.fromStr(line(80)).asInstanceOf[java.math.BigDecimal]
r.depohistTaxableprofitcost = BIGDECIMAL.fromStr(line(81)).asInstanceOf[java.math.BigDecimal]
r.depohistTermsok = INTEGER.fromStr(line(82)).asInstanceOf[java.lang.Integer]
r.depohistTurncode = INTEGER.fromStr(line(83)).asInstanceOf[java.lang.Integer]
r.depohistUsedtaxexemptions = BIGDECIMAL.fromStr(line(84)).asInstanceOf[java.math.BigDecimal]
r.depohistVHzap2 = INTEGER.fromStr(line(85)).asInstanceOf[java.lang.Integer]
r.depohistWarrantkind = INTEGER.fromStr(line(86)).asInstanceOf[java.lang.Integer]
r.depohistWarrantno = STRING.fromStr(line(87)).asInstanceOf[java.lang.String]
r.offcashcompInfo = STRING.fromStr(line(88)).asInstanceOf[java.lang.String]
r.offcashcompOpday = DATE_TIME.fromStr(line(89)).asInstanceOf[java.util.Date]
r.offcashcompOpno = INTEGER.fromStr(line(90)).asInstanceOf[java.lang.Integer]
r.offcashcompOrdno = STRING.fromStr(line(91)).asInstanceOf[java.lang.String]
r.offcashcompSsagency = STRING.fromStr(line(92)).asInstanceOf[java.lang.String]
r.offcashcompSsn = STRING.fromStr(line(93)).asInstanceOf[java.lang.String]
r.offcashcompVDnum1 = INTEGER.fromStr(line(94)).asInstanceOf[java.lang.Integer]
r.offcashcompVDsum1 = BIGDECIMAL.fromStr(line(95)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum2 = BIGDECIMAL.fromStr(line(96)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum3 = BIGDECIMAL.fromStr(line(97)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum4 = BIGDECIMAL.fromStr(line(98)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum5 = BIGDECIMAL.fromStr(line(99)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum6 = BIGDECIMAL.fromStr(line(100)).asInstanceOf[java.math.BigDecimal]
r.offcashcompVDsum7 = BIGDECIMAL.fromStr(line(101)).asInstanceOf[java.math.BigDecimal]
r.category_DPL_id = LONG.fromStr(line(102)).asInstanceOf[java.lang.Long]
r.depohistrgCpBalance = BIGDECIMAL.fromStr(line(103)).asInstanceOf[java.math.BigDecimal]
r.depohistrgCpOpcash = BIGDECIMAL.fromStr(line(104)).asInstanceOf[java.math.BigDecimal]
r.depohistrgSprBalance = BIGDECIMAL.fromStr(line(105)).asInstanceOf[java.math.BigDecimal]
r.depohistrgSprOpcash = BIGDECIMAL.fromStr(line(106)).asInstanceOf[java.math.BigDecimal]
r.depohistrgCn1Balance = BIGDECIMAL.fromStr(line(107)).asInstanceOf[java.math.BigDecimal]
r.depohistrgCn1Opcash = BIGDECIMAL.fromStr(line(108)).asInstanceOf[java.math.BigDecimal]
r.depohistrgCn2Balance = BIGDECIMAL.fromStr(line(109)).asInstanceOf[java.math.BigDecimal]
r.depohistrgCn2Opcash = BIGDECIMAL.fromStr(line(110)).asInstanceOf[java.math.BigDecimal]
r.enrollType = INTEGER.fromStr(line(111)).asInstanceOf[java.lang.Integer]
r.partition_DPL_id = LONG.fromStr(line(112)).asInstanceOf[java.lang.Long]

         r
     }
 }
            
