
 package ru.sbrf.gg.load.builder

 import ru.sbrf.gg.load.TableInfo
 import ru.sbt.kmdtransform.TransformType._

 class PublishedDepositBuilder extends ObjectBuilder {
     def build(line: Array[String], tableInfo: TableInfo): Any = {
         val r = new com.sbt.cdm.api.model.extension.PublishedDeposit()

         r.id = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.objectId = LONG.fromStr(line(0)).asInstanceOf[java.lang.Long]
r.colocationKey = LONG.fromStr(line(1)).asInstanceOf[java.lang.Long]
r.rootParticle_DPL_id = LONG.fromStr(line(2)).asInstanceOf[java.lang.Long]
r.productParty_DPL_id = LONG.fromStr(line(3)).asInstanceOf[java.lang.Long]
r.deporelationFlagKred = BOOLEAN.fromStr(line(4)).asInstanceOf[java.lang.Boolean]
r.deporelationTypeRec = LONG.fromStr(line(5)).asInstanceOf[java.lang.Long]
r.depositAccount = STRING.fromStr(line(6)).asInstanceOf[java.lang.String]
r.depositAddstate = LONG.fromStr(line(7)).asInstanceOf[java.lang.Long]
r.depositAllhistflag = LONG.fromStr(line(8)).asInstanceOf[java.lang.Long]
r.depositAloneopno = LONG.fromStr(line(9)).asInstanceOf[java.lang.Long]
r.depositArreststate = LONG.fromStr(line(10)).asInstanceOf[java.lang.Long]
r.depositAssignday = DATE_TIME.fromStr(line(11)).asInstanceOf[java.util.Date]
r.depositAssminbalance = BIGDECIMAL.fromStr(line(12)).asInstanceOf[java.math.BigDecimal]
r.depositSubsidy = BIGDECIMAL.fromStr(line(13)).asInstanceOf[java.math.BigDecimal]
r.depositInterest = BIGDECIMAL.fromStr(line(14)).asInstanceOf[java.math.BigDecimal]
r.deposit_branchno = INTEGER.fromStr(line(15)).asInstanceOf[java.lang.Integer]
r.depositCapitalday = DATE_TIME.fromStr(line(16)).asInstanceOf[java.util.Date]
r.depositCaptured = STRING.fromStr(line(17)).asInstanceOf[java.lang.String]
r.depositCapyear = LONG.fromStr(line(18)).asInstanceOf[java.lang.Long]
r.depositCashsource = INTEGER.fromStr(line(19)).asInstanceOf[java.lang.Integer]
r.depositClientkind = LONG.fromStr(line(20)).asInstanceOf[java.lang.Long]
r.depositCurrency = LONG.fromStr(line(21)).asInstanceOf[java.lang.Long]
r.depositDebtflag = BOOLEAN.fromStr(line(22)).asInstanceOf[java.lang.Boolean]
r.depositDepoflags = LONG.fromStr(line(23)).asInstanceOf[java.lang.Long]
r.depositDepositrate = BIGDECIMAL.fromStr(line(24)).asInstanceOf[java.math.BigDecimal]
r.depositDirty = BOOLEAN.fromStr(line(25)).asInstanceOf[java.lang.Boolean]
r.depositExpminbalance = BIGDECIMAL.fromStr(line(26)).asInstanceOf[java.math.BigDecimal]
r.depositIsExprOverdraft = BIGDECIMAL.fromStr(line(27)).asInstanceOf[java.math.BigDecimal]
r.depositExprOverdraftInt = BIGDECIMAL.fromStr(line(28)).asInstanceOf[java.math.BigDecimal]
r.depositFirsttwoday = DATE_TIME.fromStr(line(29)).asInstanceOf[java.util.Date]
r.deposit_tb = INTEGER.fromStr(line(30)).asInstanceOf[java.lang.Integer]
r.depositIsInterestF = BIGDECIMAL.fromStr(line(31)).asInstanceOf[java.math.BigDecimal]
r.depositIsProlongation = BOOLEAN.fromStr(line(32)).asInstanceOf[java.lang.Boolean]
r.depositKind = LONG.fromStr(line(33)).asInstanceOf[java.lang.Long]
r.depositLastkeykind = LONG.fromStr(line(34)).asInstanceOf[java.lang.Long]
r.depositLastopno = INTEGER.fromStr(line(35)).asInstanceOf[java.lang.Integer]
r.depositLastvisitday = DATE_TIME.fromStr(line(36)).asInstanceOf[java.util.Date]
r.depositLegacy = BIGDECIMAL.fromStr(line(37)).asInstanceOf[java.math.BigDecimal]
r.depositLossRights = BOOLEAN.fromStr(line(38)).asInstanceOf[java.lang.Boolean]
r.depositMaxamount = BIGDECIMAL.fromStr(line(39)).asInstanceOf[java.math.BigDecimal]
r.depositMaxamountrate = BIGDECIMAL.fromStr(line(40)).asInstanceOf[java.math.BigDecimal]
r.depositMaxoptransday = DATE_TIME.fromStr(line(41)).asInstanceOf[java.util.Date]
r.depositMbranchallowed = LONG.fromStr(line(42)).asInstanceOf[java.lang.Long]
r.depositMbranchdefault = LONG.fromStr(line(43)).asInstanceOf[java.lang.Long]
r.depositOffice = INTEGER.fromStr(line(44)).asInstanceOf[java.lang.Integer]
r.depositOpcash = BIGDECIMAL.fromStr(line(45)).asInstanceOf[java.math.BigDecimal]
r.depositOpcashrezerv = BIGDECIMAL.fromStr(line(46)).asInstanceOf[java.math.BigDecimal]
r.depositOpday = DATE_TIME.fromStr(line(47)).asInstanceOf[java.util.Date]
r.depositOpencash = BIGDECIMAL.fromStr(line(48)).asInstanceOf[java.math.BigDecimal]
r.depositOpencontrol = LONG.fromStr(line(49)).asInstanceOf[java.lang.Long]
r.depositOpenkind = LONG.fromStr(line(50)).asInstanceOf[java.lang.Long]
r.depositOpkind = INTEGER.fromStr(line(51)).asInstanceOf[java.lang.Integer]
r.depositOpno = INTEGER.fromStr(line(52)).asInstanceOf[java.lang.Integer]
r.depositOptransday = DATE_TIME.fromStr(line(53)).asInstanceOf[java.util.Date]
r.depositMinBalanceMonth = BIGDECIMAL.fromStr(line(54)).asInstanceOf[java.math.BigDecimal]
r.depositBalanceOwnProlong = BIGDECIMAL.fromStr(line(55)).asInstanceOf[java.math.BigDecimal]
r.depositIsOverdraft = BIGDECIMAL.fromStr(line(56)).asInstanceOf[java.math.BigDecimal]
r.depositOverdraftInt = BIGDECIMAL.fromStr(line(57)).asInstanceOf[java.math.BigDecimal]
r.depositP39cashprev = BIGDECIMAL.fromStr(line(58)).asInstanceOf[java.math.BigDecimal]
r.depositP39cashyear = BIGDECIMAL.fromStr(line(59)).asInstanceOf[java.math.BigDecimal]
r.depositP39day = DATE_TIME.fromStr(line(60)).asInstanceOf[java.util.Date]
r.depositP39dayprev = DATE_TIME.fromStr(line(61)).asInstanceOf[java.util.Date]
r.depositPartrate = INTEGER.fromStr(line(62)).asInstanceOf[java.lang.Integer]
r.depositPassword = STRING.fromStr(line(63)).asInstanceOf[java.lang.String]
r.depositPasswordno = LONG.fromStr(line(64)).asInstanceOf[java.lang.Long]
r.depositPayrollday = DATE_TIME.fromStr(line(65)).asInstanceOf[java.util.Date]
r.depositPayAddFirst = DATE_TIME.fromStr(line(66)).asInstanceOf[java.util.Date]
r.depositPercentsrate = BIGDECIMAL.fromStr(line(67)).asInstanceOf[java.math.BigDecimal]
r.depositPermflags = LONG.fromStr(line(68)).asInstanceOf[java.lang.Long]
r.depositProlongday = DATE_TIME.fromStr(line(69)).asInstanceOf[java.util.Date]
r.depositRatesource = LONG.fromStr(line(70)).asInstanceOf[java.lang.Long]
r.depositResident = LONG.fromStr(line(71)).asInstanceOf[java.lang.Long]
r.depositRsvdepo = STRING.fromStr(line(72)).asInstanceOf[java.lang.String]
r.depositState = INTEGER.fromStr(line(73)).asInstanceOf[java.lang.Integer]
r.depositSubkind = LONG.fromStr(line(74)).asInstanceOf[java.lang.Long]
r.depositSubscribers = LONG.fromStr(line(75)).asInstanceOf[java.lang.Long]
r.depositTerm = LONG.fromStr(line(76)).asInstanceOf[java.lang.Long]
r.depositTermsok = INTEGER.fromStr(line(77)).asInstanceOf[java.lang.Integer]
r.depositTxbranchno = LONG.fromStr(line(78)).asInstanceOf[java.lang.Long]
r.depositTxclerk = LONG.fromStr(line(79)).asInstanceOf[java.lang.Long]
r.depositTxoffice = LONG.fromStr(line(80)).asInstanceOf[java.lang.Long]
r.depositTxopcnt = LONG.fromStr(line(81)).asInstanceOf[java.lang.Long]
r.depositVServ = LONG.fromStr(line(82)).asInstanceOf[java.lang.Long]
r.metalDepositOmsMode = LONG.fromStr(line(83)).asInstanceOf[java.lang.Long]
r.depositLastkey = COMPOSEKEY.fromStr(line(84)).asInstanceOf[java.lang.Long]
r.depositOprow = COMPOSEKEY.fromStr(line(85)).asInstanceOf[java.lang.Long]
r.DepositAtSubscribeAccnt = STRING.fromStr(line(86)).asInstanceOf[java.lang.String]
r.category_DPL_id = LONG.fromStr(line(87)).asInstanceOf[java.lang.Long]
r.partition_DPL_id = LONG.fromStr(line(88)).asInstanceOf[java.lang.Long]

         r
     }
 }
            
